version: "3"

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        container_name: nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: shop
        depends_on:
            - pgsql
    pgsql:
        image: postgres:16-alpine
        restart: always
        volumes:
            - ./tmp:/var/lib/postgresql/data
            - ./docker/postgres/:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_DB: shop
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 8100:5432
        container_name: pgsql
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8090:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=bach8616@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        container_name: pgadmin
    npm:
        image: node:alpine
        container_name: npm
        volumes:
            - ./:/var/www/html
        ports:
            - 3000:5173
        working_dir: /var/www/html
        command: "npm run build"
