version: "3"

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        container_name: nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: shop-app
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: shop
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 8100:5432
        container_name: db
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8090:8080
    #     container_name: adminer
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8090:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=bach8616@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        container_name: pgadmin
