version: "3"

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        container_name: nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: shop-app
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: shop
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8100:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8090:80
        environment:
            - PMA_ARBITRARY=1
        container_name: phpmyadmin
